### ISSUE TITLE
Enable 'investor' claiming data

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/claiming-app-data#20]
### User Story
We'd like to enable investors to claim vested tokens to be able to participate in SAFE ecosystem. 

### Details
There's already an investor data supplied in this repository, however, it is only used to calculate the snapshot strategy details. Claiming data for accounts does not include investor data yet.

This proposal is to generate vesting json data for the investor accounts with the tag `investor`.

The investors' vesting pool is already initialized and contains vesting information, so this json data would be already useful for display in balances of the claiming app UIs and create claiming transactions with the ability to delegate the tokens.

### Other
Initiator: @lukasschor ([slack](https://5afe.slack.com/archives/C03DUV6DZCJ/p1666367784299479))

We must check that adding this data won't break existing web and iOS app.

**Comment by liliya-soroka** [comment]
verified
