### ISSUE TITLE
[Guardians list]The guardians logos are lost after the SEP5 data deployment

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/claiming-app-data#51]
The guardians logos are lost after the SEP5 data deployment

Open Governance app and go to the delegates list:
![image](https://github.com/safe-global/claiming-app-data/assets/338622/5aaf2dd2-1ff2-4b81-850f-d4c57e774ed5)

Make sure that the guardians logos are back

**Comment by iamacook** [comment]
Note: the guardians script is currently broken and disabling it during v2.0.x deleted the previous json.

It was manually uploaded from staging to fix the frontend.

**Comment by liliya-soroka** [comment]
Verified
the logo is back
